{
 "title": "Group Detail",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "query": "Loans" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  family, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyJourney\nWHERE\n$__timeFilter(start) \nGroup by family"
    }
   ]
  },
  {
   "title": "Availability Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(ava_debt)  as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and ava_debt > 0 and family = '$group'\n"
    }
   ]
  },
  {
   "title": "Experience Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(exp_debt)  as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and exp_debt > 0 and family='$group'\n"
    }
   ]
  },
  {
   "title": "Availability Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(lat_debt)  as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and lat_debt > 0 and family='$group'\n"
    }
   ]
  },
  {
   "title": "Availability debt count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) and family='$group'\ngroup by journey \nhaving sum(ava_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) and family='$group'\ngroup by journey \nhaving sum(ava_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability debt count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) and family='$group'\ngroup by journey\nhaving sum(exp_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) and family='$group'\ngroup by journey\nhaving sum(exp_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability debt count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) and family='$group'\ngroup by journey\nhaving sum(lat_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) and family='$group'\ngroup by journey\nhaving sum(lat_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  journey, \n  avg(ava_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and ava_debt > 0  and family='$group'\ngroup by journey",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  journey, \n  avg(exp_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and exp_debt > 0 and family='$group'\ngroup by journey",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  journey, \n  avg(lat_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and lat_debt > 0 and family='$group'\ngroup by journey",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  journey,\n  avg(nullif(ava_debt, 0)) as 'availability debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and family='$group'\ngroup by start, journey\n\n\n"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  journey,\n  avg(nullif(exp_debt, 0)) as 'experience debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and family='$group'\ngroup by start, journey\n\n\n"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  journey,\n  avg(nullif(lat_debt, 0)) as 'latency debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and family='$group'\ngroup by start, journey\n\n\n"
    }
   ]
  },
  {
   "title": "Journeys List",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT  journey, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyJourney\nWHERE\n$__timeFilter(start)  and family='$group'\nGroup by journey"
    }
   ]
  }
 ]
}