{
 "title": "Group Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Availability Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(ava_debt)   as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \n"
    }
   ]
  },
  {
   "title": "Experience Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(exp_debt)  as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \n"
    }
   ]
  },
  {
   "title": "Availability Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(lat_debt)  as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \n"
    }
   ]
  },
  {
   "title": "Availability debt group count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) \ngroup by family\nhaving sum(ava_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) \ngroup by family\nhaving sum(ava_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability debt count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) \ngroup by family\nhaving sum(exp_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) \ngroup by family\nhaving sum(exp_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability debt count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) \ngroup by family\nhaving sum(lat_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyJourney\nWHERE $__timeFilter(start) \ngroup by family\nhaving sum(lat_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  family, \n  avg(ava_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \ngroup by family",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  family, \n  avg(exp_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \ngroup by family",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  family, \n  avg(lat_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \ngroup by family",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  family,\n  avg(nullif(ava_debt, 0)) as 'availability debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) \ngroup by start, family\norder by  'availability debt'\n\n"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  family,\n  avg(nullif(exp_debt, 0)) as 'experience debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) \ngroup by start, family\norder by  'experience debt'\n\n"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  family,\n  avg(nullif(lat_debt, 0)) as 'latency debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) \ngroup by start, family\n\n\n"
    }
   ]
  },
  {
   "title": "Group List",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT  family, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyJourney\nWHERE\n$__timeFilter(start) \nGroup by family"
    }
   ]
  }
 ]
}