{
 "title": "Squad Details",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "squad", "query": "Fenix" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  squad, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlySquad\nWHERE $__timeFilter(start) \nGroup by squad"
    }
   ]
  },
  {
   "title": "Features List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT  feature, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlySquad\nWHERE \n$__timeFilter(start)  and squad = '$squad'\nGroup by feature"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "# $squad\n\nReliability debt analysis\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  ifnull(avg(nullif(ava_debt,0)),0)  as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  ifnull(avg(nullif(exp_debt,0)),0)  as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  ifnull(avg(nullif(lat_debt,0)),0)  as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  feature, \n  avg(ava_debt) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\ngroup by feature"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  feature, \n  avg(exp_debt) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\ngroup by feature"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  feature, \n  avg(lat_debt) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\ngroup by feature"
    }
   ]
  },
  {
   "title": "$squad detail",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT  feature, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlySquad\nWHERE\n$__timeFilter(start)  and squad='$squad'\nGroup by feature"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  feature,\n  avg(nullif(ava_debt, 0)) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\ngroup by start, feature"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  feature,\n  avg(nullif(exp_debt, 0)) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\ngroup by start, feature"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  feature,\n  avg(nullif(lat_debt, 0)) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and squad = '$squad'\ngroup by start, feature"
    }
   ]
  },
  {
   "title": "Source List",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT  feature,  source,\n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlySquad\nWHERE \n$__timeFilter(start)  and squad = '$squad'\nGroup by feature, source"
    }
   ]
  },
  {
   "title": "Members List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT  M.name, M.email\nFROM Squads S join SquadMembers SM on S.id = SM.squadId join Members M on SM.memberId = M.id\nWHERE squad = '$squad'\n"
    }
   ]
  }
 ]
}