{
 "title": "Squad Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Availability Squad Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT  squad, \n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt'\nFROM HourlySquad\nWHERE $__timeFilter(start) \nGroup by squad",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Squad Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT  squad, \n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt'\nFROM HourlySquad\nWHERE $__timeFilter(start) \nGroup by squad",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "LatencySquad Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT  squad, \n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'ava debt'\nFROM HourlySquad\nWHERE $__timeFilter(start) \nGroup by squad",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  squad, \n  sum(ava_debt) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \ngroup by squad",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  squad, \n  sum(exp_debt) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \ngroup by squad",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  squad, \n  sum(lat_debt) as 'debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \ngroup by squad",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  squad,\n  avg(nullif(ava_debt, 0)) as 'availability debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) \ngroup by start, squad\n"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  squad,\n  avg(nullif(exp_debt, 0)) as 'experience debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) \ngroup by start, squad\n"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  squad,\n  avg(nullif(lat_debt, 0)) as 'experience debt'\nFROM HourlySquad\nWHERE\n  $__timeFilter(start) \ngroup by start, squad\n"
    }
   ]
  },
  {
   "title": "Squad List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT  squad, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlySquad\nWHERE $__timeFilter(start) \nGroup by squad"
    }
   ]
  }
 ]
}