{
 "title": "Members Overview",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Squads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT  count(*)\nFROM Squads\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT  count(email) as total\nFROM Members\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "rawSql": "SELECT count(email) as assigned\nFROM Members M join SquadMembers SM on M.id = SM.memberId"
    }
   ]
  },
  {
   "title": "Features",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT count(*) as total\nFROM Features",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "rawSql": "SELECT count(distinct F.id) as assigned\nFROM Features F join FeatureSquads FS on F.id = FS.featureId"
    }
   ]
  },
  {
   "title": "Members per Squad",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT \n  S.squad,\n  count(SM.memberId) as members\nFROM \nSquads S join SquadMembers SM on S.id = SM.squadId\ngroup by S.squad\norder by members desc\n\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Members per feature",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT \n  F.feature,\n  count(M.id) as members\nFROM \nSquads S \njoin SquadMembers SM on S.id = SM.squadId  \njoin Members M on SM.memberId = M.id \njoin FeatureSquads FS on S.id = FS.squadId\njoin Features F on F.id = FS.featureId\ngroup by F.feature\norder by members desc\n\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Members per Journey",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT \n  J.journey,\n  count(distinct M.id) as members\nFROM \nSquads S \njoin SquadMembers SM on S.id = SM.squadId  \njoin Members M on SM.memberId = M.id \njoin FeatureSquads FS on S.id = FS.squadId\njoin Features F on F.id = FS.featureId\njoin JourneyFeatures JF on F.id = JF.featureId\njoin Journeys J on J.id  = JF.journeyId\ngroup by J.journey\norder by members desc\n\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Members List",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT  name, email, S.squad\nFROM Members M left join SquadMembers SM on M.id = SM.memberId left join Squads S on SM.squadId = S.id\n"
    }
   ]
  },
  {
   "title": "Squads List",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT  squad, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlySquad\nWHERE $__timeFilter(start) \nGroup by squad"
    }
   ]
  },
  {
   "title": "Feature List",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT  F.feature, S.squad\nfrom Features F left join FeatureSquads FS on F.id = FS.featureId left join Squads S on FS.squadId = S.id"
    }
   ]
  }
 ]
}