{
 "title": "Features Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Availability Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(ava_debt)  as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(exp_debt)  as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(lat_debt)  as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyFeature\nWHERE $__timeFilter(start) \ngroup by feature\nhaving sum(ava_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyFeature\nWHERE $__timeFilter(start) \ngroup by feature\nhaving sum(ava_debt) = 0"
    }
   ]
  },
  {
   "title": "Experience Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyFeature\nWHERE $__timeFilter(start) \ngroup by feature\nhaving sum(exp_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyFeature\nWHERE $__timeFilter(start) \ngroup by feature\nhaving sum(exp_debt) = 0"
    }
   ]
  },
  {
   "title": "Latency Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM HourlyFeature\nWHERE $__timeFilter(start) \ngroup by feature\nhaving sum(lat_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM HourlyFeature\nWHERE $__timeFilter(start) \ngroup by feature\nhaving sum(lat_debt) = 0"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  feature, \n  avg(ava_debt) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \ngroup by feature",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  feature, \n  avg(exp_debt) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \ngroup by feature",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  feature, \n  avg(lat_debt) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \ngroup by feature",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability | Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(nullif(ava_debt, 0)) as 'availability debt',\n  avg(nullif(exp_debt, 0)) as 'experience debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) \ngroup by start\n"
    }
   ]
  },
  {
   "title": "Latency Debt ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(nullif(lat_debt,0)) as 'latency debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) \ngroup by start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  ava_debt\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \nORDER BY start"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  exp_debt\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  lat_debt\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \nORDER BY start"
    }
   ]
  },
  {
   "title": "Source List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT  feature, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyFeature\nWHERE\n$__timeFilter(start) \nGroup by feature"
    }
   ]
  }
 ]
}