{
 "title": "Features Details",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "feature", "query": "Contacts" }
  ]
 },
 "panels": [
  {
   "title": "Features List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  feature, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyFeature\nWHERE\n$__timeFilter(start) \nGroup by feature"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "# $feature\n\nReliability debt analysis\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  ifnull(avg(nullif(ava_debt,0)),0)  as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start)   and feature = '$feature'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(exp_debt)  as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and exp_debt > 0  and feature = '$feature'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  ifnull(avg(nullif(lat_debt,0)),0) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  source, \n  avg(ava_debt) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\ngroup by source"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  source, \n  avg(exp_debt) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\ngroup by source"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  source, \n  avg(lat_debt) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\ngroup by source"
    }
   ]
  },
  {
   "title": "$feature detail",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT  source, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyFeature\nWHERE\n$__timeFilter(start)  and feature='$feature'\nGroup by source"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  source,\n  sum(total) as 'request'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\ngroup by source, start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  source,\n  avg(lat) as 'latency ms'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\ngroup by start, source\nORDER BY start"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  source,\n  avg(nullif(ava_debt, 0)) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\ngroup by start, source"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  source,\n  avg(nullif(exp_debt, 0)) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\ngroup by start, source"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  source,\n  avg(nullif(lat_debt, 0)) as 'debt'\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\ngroup by start, source"
    }
   ]
  },
  {
   "title": "Hourly Availability Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  ava_debt\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature' \nORDER BY start"
    }
   ]
  },
  {
   "title": "Hourly Experience Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  exp_debt\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  lat_debt\nFROM HourlyFeature\nWHERE\n  $__timeFilter(start) and feature = '$feature'\nORDER BY start"
    }
   ]
  }
 ]
}