{
 "title": "Journeys Details",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "journey", "query": "Loan Payment" },
   { "name": "feature", "query": "Dashboard" }
  ]
 },
 "panels": [
  {
   "title": "Journey List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  journey, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyJourney\nWHERE\n$__timeFilter(start) \nGroup by journey"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "options": { "content": "# $journey\n\n\n         " },
   "targets": [
    {}
   ]
  },
  {
   "title": "Leaders",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT name, email\nFROM \n  Journeys J join JourneyLeaders JL on J.id = JL.journeyId \n  join Members M on JL.memberId = M.id\nwhere J.journey = '$journey'\n\n"
    }
   ]
  },
  {
   "title": "$journey detail",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT  feature, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyJourney\nWHERE\n$__timeFilter(start)  and journey='$journey'\nGroup by feature"
    }
   ]
  },
  {
   "title": "Availability Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  ifnull(avg(nullif(ava_debt,0)),0)  as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start)   and journey = '$journey'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(exp_debt)  as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and exp_debt > 0  and journey = '$journey'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Avg Debt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(lat_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey' and lat_debt > 0\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  feature, \n  avg(ava_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey'\ngroup by feature"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  feature, \n  avg(exp_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey'\ngroup by feature"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  feature, \n  avg(lat_debt) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey'\ngroup by feature"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  feature,\n  sum(total) as 'request'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey'\ngroup by feature, start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  feature,\n  avg(lat) as 'latency ms'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey'\ngroup by start, feature\nORDER BY start"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  feature,\n  avg(nullif(ava_debt, 0)) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey'\ngroup by start, feature"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  feature,\n  avg(nullif(exp_debt, 0)) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey'\ngroup by start, feature"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  feature,\n  avg(nullif(lat_debt, 0)) as 'debt'\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey'\ngroup by start, feature"
    }
   ]
  },
  {
   "title": "Hourly Availability Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  ifnull(ava_debt,0)\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey' and ava_debt > 0\nORDER BY start"
    }
   ]
  },
  {
   "title": "Hourly Experience Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  ifnull(exp_debt,0)\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey' and exp_debt > 0\nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  ifnull(lat_debt, 0)\nFROM HourlyJourney\nWHERE\n  $__timeFilter(start) and journey = '$journey' and lat_debt > 0\nORDER BY start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 90 },
   "options": {
    "content": "# Feature:  $feature \n\nReliability debt analysis for feature\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "rawSql": "SELECT  source, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlyJourney\nWHERE\n$__timeFilter(start) and feature = '$feature'\nGroup by source"
    }
   ]
  }
 ]
}