{
 "title": "Journey Monthly SLO",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Availability Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(ava_debt)   as 'debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \n"
    }
   ]
  },
  {
   "title": "Experience Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(exp_debt)  as 'debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \n"
    }
   ]
  },
  {
   "title": "Availability Debt Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(lat_debt)  as 'debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \n"
    }
   ]
  },
  {
   "title": "Availability debt group count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM MonthlyJourney\nWHERE $__timeFilter(start) \ngroup by journey\nhaving sum(ava_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM MonthlyJourney\nWHERE $__timeFilter(start) \ngroup by journey\nhaving sum(ava_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability debt count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM MonthlyJourney\nWHERE $__timeFilter(start) \ngroup by journey\nhaving sum(exp_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM MonthlyJourney\nWHERE $__timeFilter(start) \ngroup by journey\nhaving sum(exp_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability debt count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 as 'debt'\nFROM MonthlyJourney\nWHERE $__timeFilter(start) \ngroup by journey\nhaving sum(lat_debt) > 0\n\n  \n"
    },
    {
     "rawSql": "SELECT 1 as 'no debt'\nFROM MonthlyJourney\nWHERE $__timeFilter(start) \ngroup by journey\nhaving sum(lat_debt) = 0\n"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  journey, \n  avg(ava_debt) as 'debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \ngroup by journey",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  journey, \n  avg(exp_debt) as 'debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \ngroup by journey",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  journey, \n  avg(lat_debt) as 'debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \ngroup by journey",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date(start) AS \"time\",\n  journey,\n  avg(nullif(ava_debt, 0)) as 'availability debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) \ngroup by start, journey\n\n\n"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  journey,\n  ifnull(avg(nullif(exp_debt, 0)), 0) as 'experience debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) \ngroup by start, journey\n\n\n"
    }
   ]
  },
  {
   "title": "Latecny Debt",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  journey,\n  ifnull(avg(nullif(lat_debt, 0)),0) as 'latency debt'\nFROM MonthlyJourney\nWHERE\n  $__timeFilter(start) \ngroup by start, journey\n\n\n"
    }
   ]
  },
  {
   "title": "Group Availability Debt By Month",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT  *\nFROM MonthlyAvaDebtJourneyPivot\n"
    }
   ]
  },
  {
   "title": "Group Experience Debt By Month",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT  *\nFROM MonthlyExpDebtJourneyPivot\n"
    }
   ]
  },
  {
   "title": "Group Latency Debt By Month",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT  * FROM MonthlyLatDebtJourneyPivot\n"
    }
   ]
  }
 ]
}