{
 "title": "Source Details",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "transfers/confirmation" }
  ]
 },
 "panels": [
  {
   "title": "Source List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  source, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlySource\nWHERE\n$__timeFilter(start) \nGroup by source"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "# $source\n\nReliability debt analysis\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  ifnull(avg(nullif(ava_debt,0)),0)  as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start)   and source = '$source'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(exp_debt)  as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and exp_debt > 0  and source = '$source'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  ifnull(avg(nullif(lat_debt,0)),0) as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and source = '$source'\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  sum(total) as 'request',\n  sum(ava) as 'No 5XX',\n  sum(exp) as 'No 4XX'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and source = '$source'\ngroup by start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(lat) as 'latency ms'\n  \nFROM HourlySource\nWHERE\n  $__timeFilter(start) and source = '$source'\ngroup by start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(nullif(ava_debt, 0)) as 'availability debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and source = '$source'\ngroup by start"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(nullif(exp_debt, 0)) as 'experience debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and source = '$source'\ngroup by start"
    }
   ]
  },
  {
   "title": "Latency Debt ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(lat_debt) as 'latency debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and lat_debt > 0 and source = '$source'\ngroup by start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  ava_debt\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and source = '$source'\nORDER BY start"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  exp_debt\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and source = '$source'\nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  lat_debt\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and source = '$source'\nORDER BY start"
    }
   ]
  }
 ]
}