{
 "title": "Sources Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Availability Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(ava_debt)  as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(exp_debt)  as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Avg Debt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  avg(lat_debt)  as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Top 5 Availability Debt",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  source, \n  avg(ava_debt) as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \ngroup by source\norder by debt desc\nlimit 5\n\n\n"
    }
   ]
  },
  {
   "title": "Top 5 Experience Debt",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  source, \n  avg(exp_debt) as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \ngroup by source\norder by debt desc\nlimit 5"
    }
   ]
  },
  {
   "title": "Top 5 Availability Debt",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  source, \n  avg(lat_debt) as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \ngroup by source\norder by debt desc\nlimit 5"
    }
   ]
  },
  {
   "title": "Availability | Experience Debt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(nullif(ava_debt, 0)) as 'availability debt',\n  avg(nullif(exp_debt, 0)) as 'experience debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) \ngroup by start\n"
    }
   ]
  },
  {
   "title": "Latency Debt ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(nullif(lat_debt,0)) as 'latency debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) \ngroup by start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  sum(total) as 'request',\n  sum(ava) as 'No 5XX',\n  sum(exp) as 'No 4XX'\nFROM HourlySource\nWHERE\n  $__timeFilter(start)\ngroup by start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  avg(lat) as 'latency ms'\n  \nFROM HourlySource\nWHERE\n  $__timeFilter(start)\ngroup by start\nORDER BY start"
    }
   ]
  },
  {
   "title": "Availability Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  source, \n  avg(ava_debt) as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \ngroup by source",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Experience Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  source, \n  avg(exp_debt) as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \ngroup by source",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency Debt Map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  source, \n  avg(lat_debt) as 'debt'\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \ngroup by source",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Availability Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  ava_debt\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and ava_debt > 0 \nORDER BY start"
    }
   ]
  },
  {
   "title": "Experience Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  exp_debt\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and exp_debt > 0 \nORDER BY start"
    }
   ]
  },
  {
   "title": "Latency Debt",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  lat_debt\nFROM HourlySource\nWHERE\n  $__timeFilter(start) and lat_debt > 0 \nORDER BY start"
    }
   ]
  },
  {
   "title": "Source List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT  source, \n        max(avaSlo) as 'ava slo',\n        ifnull(AVG(NULLIF(ava_debt ,0)),0) as 'ava debt',\n        max(expSlo) as 'exp slo',\n        ifnull(AVG(NULLIF(exp_debt ,0)),0) as 'exp debt',\n        max(latSlo) as 'lat slo',\n        ifnull(AVG(NULLIF(lat_debt ,0)),0) as 'lat debt'\nFROM HourlySource\nWHERE\n$__timeFilter(start) \nGroup by source"
    }
   ]
  }
 ]
}